name: workflow-1
on: [push]
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls -al
      - run: docker build --tag img:latest .
  
  test-application:
    runs-on: ubuntu-latest
    steps:
      - run: python .